### ISSUE TITLE
Add signal trap

### ISSUE THREAD

**Issue by ivany4** [carlossless/tangerine#4]
There should be a signal trap that closes a keychain on script completion.
Right now, if the script crashes in the middle, the keychain is left open.

**Comment by carlossless** [comment]
PR's are welcome! :+1:

**Comment by ivany4** [comment]
As soon as I get some spare time, friend! ;)

**Comment by carlossless** [comment]
Did you test with a failure case?

**Comment by ivany4** [comment]
Yes.

**Comment by carlossless** [comment]
Confirmed, thank you! :kiss: lol
